In [32]:
import numpy as np

### 1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado ```altura_em_centimetros``` transformando a lista ```lista_de_alturas``` em um ndarray do numpy com a função ```np.array()```  
ii. Crie um outro objeto ```altura_em_metros```, com os valores de ```altura_em_centimetros``` convertidos para metros.

In [35]:
lista_de_centimetros = list(range(170, 190, 5))
lista_de_centimetros

[170, 175, 180, 185]

In [58]:
altura_em_centimetros = np.array([170, 190, 5])
lista_de_centimetros = altura_em_centimetros / 2.54
lista_de_centimetros

array([66.92913386, 74.80314961,  1.96850394])

In [60]:
altura_em_metros = lista_de_centimetros * 0.01
lista_de_alturas = altura_em_metros * 12
lista_de_alturas

array([8.03149606, 8.97637795, 0.23622047])

### 2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos ```lista_pesos = [70, 75, 80, 85]```. Crie um **ndarray** chamado ```pesos``` com a função ```np.array()``` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado ```imc```.

In [62]:
lista_de_pesos = lista_de_alturas * 2.20462
lista_de_pesos

array([17.70639685, 19.78950236,  0.52077638])

In [64]:
def calcular_imc(lista_de_peso, lista_de_altura):
    imc = lista_de_peso / (lista_de_altura ** 2)
    return imc


# Exemplo de uso
lista_de_peso = 70  # em quilogramas
lista_de_altura = 1.75  # em metros

imc = calcular_imc(lista_de_peso, lista_de_altura)
print(f"O IMC é: {imc:.2f}")

#calcule o codido IMC

O IMC é: 22.86


### 3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [79]:
# lista dados_financeiros
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
dados_financeiros = np.array(dados_financeiros)
print(dados_financeiros)
#i) tansforme esse lista em ndarray

[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500  7000 16000]]


In [103]:
# ii)
dados_financeiros_transposta = np.transpose(dados_financeiros)

print("dados_financeiros:")
print(dados_financeiros)
print("\ndado_financeiros transposta:")
print(dados_financeiros_transposta)

dados_financeiros:
[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500  7000 16000]]

dado_financeiros transposta:
[[ 3000  1000  6000]
 [ 2500  2500  5500]
 [ 1000  3000  7000]
 [10000  5000 16000]]


In [115]:
# Assuming `dados_financeiros` is provided and is a numerical value

try:
    # Calculate total indebtedness
    endividamento_total = dados_financeiros / 10000
    print(f"Endividamento Total: {endividamento_total}")
except TypeError:
    print("Erro: 'dados_financeiros' deve ser um número.")


Endividamento Total: [[0.3  0.25 0.1  1.  ]
 [0.1  0.25 0.3  0.5 ]
 [0.6  0.55 0.7  1.6 ]]


In [117]:
# Dados financeiros exemplo
dados_financeiros = [
    {"dados_financeiros": 5000, "endividamento_total": 500},
    {"dados_financeiros": 7000, "endividamento_total": 2000},
    {"dados_financeiros": 7000, "endividamento_total": 4000},
]

# Corrigindo a renda do terceiro indivíduo
dados_financeiros[2]["dados_financeiros"] = 10000

# Cálculo do endividamento total
endividamento_total = sum(individuo["endividamento_total"] for individuo in dados_financeiros) / 10000

# Exibindo o resultado
print(endividamento_total)

# iv) corrigindo um valor específico

0.65


### 4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os. 

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [119]:
# objeto poi - obs: o comando np.random.seed(1234) garante que o mesmo resultado será gerado sempre
np.random.seed(1234)
poi = np.random.poisson(3, 100)
poi

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 0, 3, 3, 2, 8, 2, 3, 3, 3, 0, 4, 4, 2,
       6, 6, 0, 3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3,
       2, 2, 3, 6, 2, 2, 4, 3, 5, 2, 5, 3, 0, 2, 1, 1, 4, 4, 4, 6, 2, 4,
       1, 2, 5, 5, 3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 0, 4, 4, 0, 6, 1,
       3, 4, 2, 5, 4, 5, 5, 3, 4, 6, 8, 2])

In [121]:
import numpy as np

# Supondo que o seu array poi seja definido como algo assim
poi = np.array([0, 1, 2, 0, 3, 0, 4])

# Criando o array booleano bool_zero com o operador ==
bool_zero = (poi == 0)

print(bool_zero)

# i) crie o objeto bool_zero através do operador ==

[ True False False  True False  True False]


In [123]:
# ii) Conte a quantidade de zeros (ou some os elementos de bool_zero)
bool_zero = (poi * 0)
print(bool_zero)

[0 0 0 0 0 0 0]


In [125]:
# Utilizando indexação booleana para obter os elementos de 'poi' diferentes de zero
poi_nao_zero = poi[poi != 0]

print(poi_nao_zero)


# iii) utilize a indexação booleana para criar uma seleção de não-zeros
# dica: inverta o objeto bool_zero

[1 2 3 4]
